### ISSUE TITLE
multiple CIKs for cusip 94311218

### ISSUE THREAD

**Issue by LurkingVariable** [leoliu0/cik-cusip-mapping#3]
Hi 
Thanks for making this mapping available to everyone. It is extremely useful. I noticed what I think is a small bug in the output. It seems cusip8 "94311218" occurs 1,388 times in the output file and appears to map to a different CIK each time. cusip8 "94311218" doesn't appear to match any security on https://quotes.fidelity.com/ftgw/fbc/ofquotes/mmnet/SymLookup. Is it a placeholder? Thanks again.

**Comment by leoliu0** [comment]
Hi,
Thanks for pointing this out. After some investigation, I find these are IRS numbers wrongly captured by the algorithm. I have rectified the error and pushed a new version. 

There are some other junks in there too. I cleaned the obvious ones but a full cleaning is very difficult. One could cross-reference other sources like the one you mentioned.

Please open a new issue you find something else. Thanks.
