### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by leocanada2007** [leoliu0/cik-cusip-mapping#9]
Hi Leo, 

I am using the program to download NPORT-P files. After running dl_index.py, I see roughly 150000 NPORT-P entries from full_index.csv, but I am only able to download about 50000 entries after running dl.py. Could you please help with that? I am new to Python, so maybe I am missing something here. 

Looking forward to your reply.

Thanks, 

Leo

**Comment by leoliu0** [comment]
Hi Leo,

What do you mean by only being able to download 50,000? Is it stop at 50,000 and unable to proceed, or it is some reason. Please specify the error message you received for me to look further.

Thanks

**Comment by leocanada2007** [comment]
Hi Leo, 

Thanks for your reply. I do not see any error message. Specifically, I see "print(f"{n} out of {len_}")" printed out for each of my 150,000+ entries, and I never see "print(f"{cik}, {date} failed to download")". 

I dig a bit more into the issue, and here is what I think: since the text files are named as "/{folder}/{year}_{month}/{cik}_{date}.txt", so if the same company (cik) submitted several NPORT-P forms on the same day (which is not rare, as can be seen from the full_index file), only the first text file will be saved.

Can you think of a quick fix? Thanks again!

Leo

**Comment by leoliu0** [comment]
I see. This is a bug that I worry about some times ago. This case is rare for 13D/G filings but may be prevalent for other filings. I will push a fix soon

**Comment by leocanada2007** [comment]
Thanks! Looking forward to it!

**Comment by leoliu0** [comment]
By adding the access number to file name, should fix the issue. Please download the latest version to try. You can re-open this issue if things are still not right
